name: todo_list_cal
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1 
  table_calendar: ^3.1.2
  intl: ^0.19.0 
  provider: ^6.1.2 
  fluttertoast: ^8.2.6
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/LogoF.png


  uses-material-design: true

